Error: near line 1: attempt to write a readonly database
Error: near line 1: attempt to write a readonly database
2020-04-06 22:47:04.965115: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /software/tamusc/Anaconda/3-5.0.0.1/lib:/software/lsf/9.1/linux2.6-glibc2.3-x86_64/lib
2020-04-06 22:47:04.965362: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /software/tamusc/Anaconda/3-5.0.0.1/lib:/software/lsf/9.1/linux2.6-glibc2.3-x86_64/lib
2020-04-06 22:47:04.965390: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-04-06 22:47:23.764870: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /software/tamusc/Anaconda/3-5.0.0.1/lib:/software/lsf/9.1/linux2.6-glibc2.3-x86_64/lib
2020-04-06 22:47:23.765723: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-04-06 22:47:23.765810: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (nxt1149): /proc/driver/nvidia/version does not exist
2020-04-06 22:47:23.776959: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494145000 Hz
2020-04-06 22:47:23.778094: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561940675f90 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-06 22:47:23.778129: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/home/skumar55/.lsbatch/1586231163.10358949.shell: line 20: 22622 Killed                  python classify.py
